### PR TITLE
CMake integration (subset from obs-studio)

### PR DESCRIPTION
**Pull request by ChristianFrisson**

### CODE REVIEW

**Comment by ChristianFrisson** [comment]
Partially closing pull request https://github.com/jp9000/libdshowcapture/pull/4 .

**Comment by jp9000** [comment]
Works great, though could you add an option to build shared as well?

**Comment by ChristianFrisson** [comment]
OK, done with the standard UILD_SHARED_LIBS option.

**Comment by jp9000** [comment]
Nice, thank you.  Merging with minor changes to the commit messages (commit messages should be 50/72 format, and need to be present tense rather than past tense)

**Pull request closed without merging**
